
kp_tab: CHAIN_OPTIONS
alt_l: PRESET
escape: SCREEN_AUDIO_MIXER
backspace: ZYNSWITCH 1
kp_enter: ZYNSWITCH 3

kp_divide: SCREEN_ZYNPAD
kp_multiply: SCREEN_PATTERN_EDITOR
kp_add: TOGGLE_MIDI_PLAY
kp_subtract: TOGGLE_MIDI_RECORD

kp_home: SCREEN_SNAPSHOT
kp_prior: SCREEN_MIDI_RECORDER
kp_next: ENTER_MIDI_LEARN
kp_begin: ZYNSWITH 0
kp_end: ZYNSWITCH 1

kp_up: ARROW_UP
kp_down: ARROW_DOWN
kp_left: ARROW_LEFT
kp_right: ARROW_RIGHT

kp_insert: SCREEN_AUDIO_MIXER
kp_0: SCREEN_ALSA_MIXER
kp_delete: MENU
kp_decimal: SCREEN_ADMIN


