space 0: ALL_NOTES_OFF
space 1: ALL_SOUNDS_OFF

home 1: RESTART_UI
home 4: REBOOT
end 4: POWER_OFF
insert 4: RELOAD_MIDI_CONFIG

i: ZYNSWITCH 0
k: ZYNSWITCH 1
backspace: ZYNSWITCH 1
escape: ZYNSWITCH 1
o: ZYNSWITCH 2
l: ZYNSWITCH 3
return: ZYNSWITCH 3

period 4: ZYNPOT 1,1
comma 4: ZYNPOT 1,-1
period 0: ZYNPOT 3,1
comma 0: ZYNPOT 3,-1
greater 5: ZYNPOT 0,1
less 5: ZYNPOT 0,-1
greater 1: ZYNPOT 2,1
less 1: ZYNPOT 2,-1

a 0: START_AUDIO_RECORD
a 1: STOP_AUDIO_RECORD
a 8: TOGGLE_AUDIO_RECORD
a 4: START_AUDIO_PLAY
a 5: STOP_AUDIO_PLAY
a 12: TOGGLE_AUDIO_PLAY

m 0: START_MIDI_RECORD
m 1: STOP_MIDI_RECORD
m 8: TOGGLE_MIDI_RECORD
m 4: START_MIDI_PLAY
m 5: STOP_MIDI_PLAY
m 12: TOGGLE_MIDI_PLAY

down 0: ARROW_DOWN
up 0: ARROW_UP
right 0: ARROW_RIGHT
left 0: ARROW_LEFT

1: PROGRAM_CHANGE 1
2: PROGRAM_CHANGE 2
3: PROGRAM_CHANGE 3
4: PROGRAM_CHANGE 4
5: PROGRAM_CHANGE 5
6: PROGRAM_CHANGE 6
7: PROGRAM_CHANGE 7
8: PROGRAM_CHANGE 8
9: PROGRAM_CHANGE 9
0: PROGRAM_CHANGE 0
